### ISSUE TITLE
Getting ETIMEDOUT on version check

### ISSUE THREAD

**Issue by soundstep** [denoland/setup-deno#34]
Hi, we're seeing some error in the the Github Action runs.
It seems trying to get this URL: https://raw.githubusercontent.com/denoland/deno_website2/main/versions.json
And the error seems to be intermittent.

<img width="1295" alt="Screenshot 2022-10-11 at 11 10 14" src="https://user-images.githubusercontent.com/133293/195064375-67cac845-3534-4e59-9cbd-a7a8535e3679.png">

Any idea?

**Comment by lucacasonato** [comment]
This happens when parts of GitHub are down.
