### ISSUE TITLE
Verified Creator on Github Marketplace

### ISSUE THREAD

**Issue by shinebayar-g** [denoland/setup-deno#42]
Have you considered becoming a verified creator on [Github Marketplace](https://github.com/marketplace?type=actions&verification=verified_creator)? Due to corporate policy we're not allowed to use 3rd party Actions.

**Comment by lucacasonato** [comment]
The action is now verified: 
<img width="1440" alt="image" src="https://github.com/denoland/setup-deno/assets/7829205/101a6a57-9421-4c0a-89a4-5db78472399a">
