### ISSUE TITLE
Stuck at Deno 1.33.1

### ISSUE THREAD

**Issue by wojpawlik** [denoland/setup-deno#48]
https://github.com/kt3k/deno-bin/actions/runs/5340170567/jobs/9679669961#step:3:3

**Comment by crowlKats** [comment]
it should not be locked to 1.0.0; there was a change in our setup and since then, new versions arent available if not using 1.1.2 or above. We recommend unpinning from patch & minor and just use `1`

**Comment by crowlKats** [comment]
cc @kt3k

**Comment by kt3k** [comment]
Thanks for your report and help.

Relaxed the version specifier of setup-deno in deno-bin repo https://github.com/kt3k/deno-bin/commit/66b1c090fba1264596b924eaf684a60f11cd3c77

Now 1.34.3 got published https://www.npmjs.com/package/deno-bin/v/1.34.3
