### ISSUE TITLE
Setup a `v1` tag that points to the latest version of the action

### ISSUE THREAD

**Issue by mikokofuyu** [denoland/setup-deno#51]
We noticed recently in one of our projects that our GHA wasn't pulling through the correct version of `denoland/setup-deno` I believe this is because there isn't `major` and `minor` version tags setup that points to the same ref as the most recent version. e.g `v1` / `v1.1`

For example: https://github.com/actions/checkout/tags

As mentioned in `3.` here: https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#example-developer-process

**Comment by lucab** [comment]
Thanks for the report.
We do use the [branching approach](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-branches-for-release-management) for release management (without moveable tags), and we do maintain this `v1` branch to roll `denoland/setup-deno@v1` forward: https://github.com/denoland/setup-deno/tree/v1

At the time of your writing, the tip of the branch was still at 1.1.2 as we forgot to bump to 1.1.3.
I've just re-synced that branch, so your CI jobs should now be able to use the latest release.
I'm closing this now, please let us know in case you still encounter issues related to this.
