### ISSUE TITLE
Node16 is deprecated and action will not run

### ISSUE THREAD

**Issue by ctdeakin** [denoland/setup-deno#55]
Error message: Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: denoland/setup-deno@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by bjesuiter** [comment]
Should be fixed when #56 is merged 
(I know, it's your own PR, I only want to link it for better discoverability ^^)

**Comment by lucacasonato** [comment]
This is fixed in 1.1.4
