### ISSUE TITLE
404 from download url https://github.com/denoland/deno/releases/download...

### ISSUE THREAD

**Issue by russorat** [denoland/setup-deno#6]
i was using `denoland/setup-deno@main` and started getting a 404 for the URL not working. 
https://github.com/denoland/deno/releases/download/v1.11.1/deno-x86_64-unknown-linux-gnu.zip

https://github.com/influxdata/influxdb2-sample-data/runs/2834094631?check_suite_focus=true#step:2:5

i fixed it by using `denoland/setup-deno@v1` which uses https://dl.deno.land/release/v1.11.1/deno-x86_64-unknown-linux-gnu.zip to download deno.

**Comment by satyarohith** [comment]
The assets are now released. `GET https://github.com/denoland/deno/releases/download/v1.11.1/deno-x86_64-unknown-linux-gnu.zip` doesn't return 404 anymore.
