### ISSUE TITLE
`deno-version: stable` doesn't work

### ISSUE THREAD

**Issue by littledivy** [denoland/setup-deno#79]
The README says it works:

> Valid values are stable, canary and rc.

 https://github.com/denoland/setup-deno?tab=readme-ov-file#determining-the-release-channel

Maybe remove the docs since it defaults to stable when `deno-version` is not provided?

**Comment by lucacasonato** [comment]
@littledivy You did not read the docs right. This is in a section titled `Determining the release channel`.

It says:

> You can determine the release channel reading back the `release-channel` output.
> 
> Valid values are `stable`, `canary` and `rc`.

So `stable` is a valid value for the `release-channel` **output**, not for `deno-version` input.

**Comment by littledivy** [comment]
Whoops!

**Comment by tcely** [comment]
Stable is listed in the input section also.

It still doesn't work.

According to the code `latest` does seem to work.

https://github.com/denoland/setup-deno#version-from-input

Either the documentation needs to be updated or the code needs to accept `stable`, in my opinion.
